export const REFERENCE_JOBS = [
  {
    jobId: 'job-demo-001',
    jobReference: 'SHIP-DEMO-001',
    customerName: 'Intercont Freight Liners Pvt. Ltd.',
    route: 'INNSA -> AEKLF',
    vessel: 'SSL GODAVARI / 056',
    blNumber: 'NSAKLF26145311',
    containers: ['OTPU6719060'],
    containerType: '40HC x 1',
    invoiceAccruals: {
      '27INSA2606031446/UAI': [
        { chargeCode: 'BLC', chargeDescription: 'Bill Of Lading Charges', amount: 4000, keywords: ['bill of lading'] },
        { chargeCode: 'EWR', chargeDescription: 'Emergency War Risk Surcharge', amount: 4933, keywords: ['war risk'] },
        { chargeCode: 'IDC', chargeDescription: 'Infrastructure & Development Charges', amount: 50, keywords: ['infrastructure'] },
        { chargeCode: 'MUC', chargeDescription: 'Mandatory User Charges', amount: 170, keywords: ['mandatory user'] },
        { chargeCode: 'THC', chargeDescription: 'POL Terminal Handling Charges', amount: 34450, keywords: ['terminal handling', 'pol terminal'] },
        { chargeCode: 'SEL', chargeDescription: 'Seal Charges', amount: 750, keywords: ['seal'] },
        { chargeCode: 'SWB', chargeDescription: 'SWB', amount: 3500, keywords: ['swb'] },
        { chargeCode: 'TOL', chargeDescription: 'Toll Fee', amount: 1198, keywords: ['toll'] },
      ],
      '27INSA2606031447/UAI': [
        { chargeCode: 'AFR', chargeDescription: 'Additional Freight Charges', amount: 100633.2, keywords: ['additional freight'] },
        { chargeCode: 'BAF', chargeDescription: 'Bunker Adjustment Factor', amount: 75474.9, keywords: ['bunker'] },
        { chargeCode: 'CRS', chargeDescription: 'Cost Recovery Surcharge', amount: 39464, keywords: ['cost recovery'] },
        { chargeCode: 'EMS', chargeDescription: 'Emergency Surcharge', amount: 285980, keywords: ['emergency surcharge'] },
        { chargeCode: 'OFR', chargeDescription: 'Ocean Freight', amount: 75474.9, keywords: ['ocean freight'] },
      ],
    },
    accruals: [],
  },
  {
    jobId: 'job-demo-002',
    jobReference: 'SHIP-DEMO-002',
    customerName: 'Intercont Freight Liners Pvt. Ltd.',
    route: 'Ho Chi Minh -> Nhava Sheva',
    vessel: 'HALLEY / 012E',
    blNumber: 'COAU7269669782',
    containers: ['FBIU5456563'],
    containerType: '40RQ x 1',
    invoiceAccruals: {
      CIEX272606000442: [
        { chargeCode: 'TOL', chargeDescription: 'Toll Charges', amount: 1200, keywords: ['toll'] },
        { chargeCode: 'MUC', chargeDescription: 'Mandatory User Charge', amount: 170, keywords: ['mandatory user'] },
        { chargeCode: 'THC', chargeDescription: 'Origin Terminal Handling', amount: 31350, keywords: ['orig trml', 'terminal'] },
        { chargeCode: 'REF', chargeDescription: 'Reefer Variance Charges', amount: 4236, keywords: ['reefer'] },
        { chargeCode: 'SEL', chargeDescription: 'Seal Fee', amount: 492, keywords: ['seal'] },
        { chargeCode: 'DOC', chargeDescription: 'Origin Documentation Fee', amount: 4500, keywords: ['doc fee', 'documentation'] },
      ],
      CIEX272606000454: [
        { chargeCode: 'OFR', chargeDescription: 'Ocean Freight', amount: 72838, keywords: ['ocean freight'] },
      ],
    },
    accruals: [],
  },
  {
    jobId: 'job-demo-003',
    jobReference: 'SHIP-DEMO-003',
    customerName: 'Intercont Freight Liners Pvt. Ltd.',
    route: 'Jawaharlal Nehru -> Port Louis',
    vessel: 'SAVANNAH EXPRESS / 627W',
    blNumber: '272615066',
    containers: [
      'MMAU1138025',
      'MMAU1257169',
      'MNBU0284111',
      'MNBU3046349',
      'MNBU3158014',
      'MNBU3235168',
      'MNBU3467559',
      'MNBU3578505',
      'SUDU6006520',
      'SUDU6088575',
      'SUDU6175242',
      'SUDU6205368',
      'SUDU8190210',
    ],
    containerType: "40'6 Reefer x 13",
    invoiceAccruals: {
      MH27IN1000616149: [
        { chargeCode: 'EXP', chargeDescription: 'Export Service', amount: 143, keywords: ['export service'] },
      ],
    },
    accruals: [],
  },
  {
    jobId: 'job-demo-004',
    jobReference: 'SHIP-DEMO-004',
    customerName: 'Intercont Freight Liners Pvt. Ltd.',
    route: 'Nhava Sheva -> Port Kelang',
    vessel: 'SEASPAN BRISBANE / E021',
    blNumber: 'HLCUBO1260500261',
    containers: ['HLXU8767243'],
    containerType: "40'6 Reefer x 1",
    invoiceAccruals: {
      MH11953184: [
        { chargeCode: 'OFR', chargeDescription: 'Freight', amount: 300, keywords: ['freight'] },
      ],
    },
    accruals: [],
  },
  {
    jobId: 'job-demo-005',
    jobReference: 'SHIP-DEMO-005',
    customerName: 'Intercont Freight Liners Pvt. Ltd.',
    route: 'Nhava Sheva -> Fujairah',
    vessel: 'CMA CGM VITORIA / 0UW2VW1MA',
    blNumber: 'AMC2552268',
    containers: ['CGMU5139012', 'CGMU5361251', 'CXRU1601296', 'TCLU1266204', 'TEMU9548520', 'TTNU8606923', 'TTNU8979594'],
    containerType: '40RH x 7',
    invoiceAccruals: {
      INEMHC27044516: [
        { chargeCode: 'OFR', chargeDescription: 'Basic Ocean Freight', amount: 9352, keywords: ['basic ocean freight'] },
        { chargeCode: 'BAF', chargeDescription: 'Bunker Adjustment Factor', amount: 1344, keywords: ['bunker'] },
        { chargeCode: 'EFS', chargeDescription: 'Emergency Fuel Surcharge', amount: 2170, keywords: ['emergency fuel'] },
        { chargeCode: 'ERC', chargeDescription: 'Extra Risk Coverage Surcharge at destination', amount: 504, keywords: ['extra risk'] },
        { chargeCode: 'ECS', chargeDescription: 'Emergency Conflict Surcharge', amount: 14000, keywords: ['emergency conflict'] },
      ],
    },
    accruals: [],
  },
  {
    jobId: 'job-demo-006',
    jobReference: 'SHIP-DEMO-006',
    customerName: 'Intercont Freight Liners Pvt. Ltd.',
    route: 'Nhava Sheva -> Fujairah',
    vessel: 'WADI ALRAYAN / 0UW3XW1MA',
    blNumber: 'AMC2547828',
    containers: ['CGMU5363233', 'TCLU1330284'],
    containerType: '40RH x 2',
    invoiceAccruals: {
      INEMHC27047899: [
        { chargeCode: 'THC', chargeDescription: 'Terminal Handling Charge at origin', amount: 67050, keywords: ['terminal handling'] },
        { chargeCode: 'ISS', chargeDescription: 'ISPS Vessel Security Surcharge', amount: 2755.48, keywords: ['isps'] },
        { chargeCode: 'TRK', chargeDescription: 'On Carriage Haulage', amount: 0, keywords: ['on carriage'] },
        { chargeCode: 'DRY', chargeDescription: 'Terminal drayage Fee at destination', amount: 472369.2, keywords: ['terminal drayage'] },
        { chargeCode: 'SEL', chargeDescription: 'Sealing service export', amount: 1968.2, keywords: ['sealing'] },
        { chargeCode: 'DOC', chargeDescription: 'Documentation Fee at origin', amount: 5100, keywords: ['documentation'] },
      ],
    },
    accruals: [],
  },
];

export const KNOWN_CHARGES = [
  { code: 'OFR', description: 'Ocean Freight', keywords: ['ocean freight', 'freight', 'ofr'] },
  { code: 'BAF', description: 'BAF Surcharge', keywords: ['baf', 'bunker'] },
  { code: 'DOC', description: 'Documentation Fee', keywords: ['documentation', 'document', 'doc'] },
  { code: 'PHC', description: 'Port Handling Charge', keywords: ['port handling', 'phc'] },
  { code: 'THC', description: 'Terminal Handling Charge', keywords: ['terminal handling', 'thc'] },
  { code: 'PSS', description: 'Peak Season Surcharge', keywords: ['peak season', 'pss'] },
  { code: 'TRK', description: 'Trucking', keywords: ['trucking', 'transport', 'haulage'] },
  { code: 'FUL', description: 'Fuel Surcharge', keywords: ['fuel'] },
  { code: 'LAB', description: 'Labour Charges', keywords: ['labour', 'labor'] },
  { code: 'SEL', description: 'Seal Charge', keywords: ['seal'] },
];
